### ISSUE TITLE
fix: using instanceof with generics

### ISSUE THREAD

**Issue by ZeRiix** [duplojs/core#93]
## Description
There is an issue with using `instanceof` to check instances of `duploses`. A `duplose` instance can either be a `Route` or a `Process`. The only way to differentiate between them is by using a condition. However, using `instanceof` with a class that has generics results in all generics being treated as `any`, which prevents access to the `Route` definition later on.

### Affected Code
```ts
...
await duplo.launch();

console.log(`Server is running on http://${duplo.config.host}:${duplo.config.port}`);

console.log("Routes:");
duplo.duploses.forEach((duplose) => {
    if (!(duplose instanceof Route)) return;
    console.log(
        duplose.definition.method,
        `http://${duplo.config.host}:${duplo.config.port}${duplose.definition.paths[0]}`
    );
});
```

### Problematic part:
```ts
if (!(duplose instanceof Route)) return;
console.log(duplose.definition.method);
```

### Current Semi-Correction Solution:

```ts
if (duplose instanceof Route) {
    const route = duplose as Route<RouteDefinition>;
    console.log(route.definition.method);
}
```

**Comment by mathcovax** [comment]
the solution is to create a function that replaces instanceof for duploses:

```ts
const testRoute: Duplose<any, any, any>;

if (instanceofDuplose(Route, testRoute)) {
    // testRoute === Route<RouteDefinition, Request, object>;
}
else {
    // testRoute === Duplose<any, any, any>;
}
```
